spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/multivendor_db
spring.datasource.username=multivendor_user
spring.datasource.password=multivendor123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
